# Numpy exercices pratiques
Ce notebook à pour objectif de vous faire pratiquer numpy dans toute sa généralité. 
Vous avez donc une liste de questions à faire ! Il ne faut pas hésiter à faire des recherches sur google ainsi que voir la [documentation officielle](https://docs.scipy.org/doc/numpy-1.13.0/reference/). 

#### Q1 : Importer le package numpy 

In [1]:
import numpy as np

#### Q2 : Afficher la version de numpy et la configuration 

In [2]:
print(np.__version__)
print(np.show_config())

1.19.2
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
None


#### Q3 : Créer un vecteur nul de taille 10

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Q4 : Créer un vecteur null de taille 10 et affecter la valeur 1 à la 4ème place (index 4) du vecteur

In [8]:
z = np.zeros(10); z


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
z[3]=1; z

array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])

#### Q5 : Créer un vecteur Z de 40 valeurs allant de 10 à 50 

In [16]:
z = np.linspace(10,50,40); z

array([10.        , 11.02564103, 12.05128205, 13.07692308, 14.1025641 ,
       15.12820513, 16.15384615, 17.17948718, 18.20512821, 19.23076923,
       20.25641026, 21.28205128, 22.30769231, 23.33333333, 24.35897436,
       25.38461538, 26.41025641, 27.43589744, 28.46153846, 29.48717949,
       30.51282051, 31.53846154, 32.56410256, 33.58974359, 34.61538462,
       35.64102564, 36.66666667, 37.69230769, 38.71794872, 39.74358974,
       40.76923077, 41.79487179, 42.82051282, 43.84615385, 44.87179487,
       45.8974359 , 46.92307692, 47.94871795, 48.97435897, 50.        ])

#### Q6 : Inverser Z (le premier élément devient donc le dernier)

In [23]:
z=np.linspace(10,50,40);z
c=np.flip(z);c

array([50.        , 48.97435897, 47.94871795, 46.92307692, 45.8974359 ,
       44.87179487, 43.84615385, 42.82051282, 41.79487179, 40.76923077,
       39.74358974, 38.71794872, 37.69230769, 36.66666667, 35.64102564,
       34.61538462, 33.58974359, 32.56410256, 31.53846154, 30.51282051,
       29.48717949, 28.46153846, 27.43589744, 26.41025641, 25.38461538,
       24.35897436, 23.33333333, 22.30769231, 21.28205128, 20.25641026,
       19.23076923, 18.20512821, 17.17948718, 16.15384615, 15.12820513,
       14.1025641 , 13.07692308, 12.05128205, 11.02564103, 10.        ])

#### Q7 : Créer une matrice 3x3 avec des valeurs comprise entre 0 et 8 

In [28]:
a = np.linspace(0,8,9); a
a.shape=(3,3) ;a

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

#### Q8 : Créer une matrice identié 3x3 

In [30]:
a = np.diag(np.ones(3)) ; a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Q9 : Créer une matrice 3x3x3 avec des valeurs random 

In [39]:
c=np.zeros(27).reshape(3,3,3); c
c = np.random.rand(3,3,3); c

array([[[0.15090969, 0.58671161, 0.71370853],
        [0.71589301, 0.60048028, 0.3209045 ],
        [0.00934232, 0.83835765, 0.11447404]],

       [[0.01337532, 0.44750463, 0.20758547],
        [0.52481634, 0.79767909, 0.43381778],
        [0.7745206 , 0.21694965, 0.05320272]],

       [[0.18556672, 0.38122863, 0.68828683],
        [0.67578199, 0.15037281, 0.85803499],
        [0.77578965, 0.68351418, 0.04742262]]])

#### Q10 : Créer une matrice 10x10 avec des valeurs random et afficher le minimum et maximum de cette matrice

In [44]:
c = np.random.rand(10,10);
c.max()


0.9907036253326374

In [43]:
c.min()

0.013014418901633684

#### Q11 : Créer une matrice 5x5 avec les valeurs 1,2,3,4 en dessous de la diagonale 

In [54]:
a = np.diag(np.ones(5)) ; a
a[1,0]=1
a[2,1]=2
a[3,2]=3
a[4,3]=4; a

array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [0., 2., 1., 0., 0.],
       [0., 0., 3., 1., 0.],
       [0., 0., 0., 4., 1.]])

#### Q12 : Créer une liste random de taille 5 et donner la somme de ses éléments  

In [50]:
x = np.random.rand(5); x
x.sum()

3.4314674601544324

#### Q13 : Créer une liste random de taille 5 et donner la moyenne de ses éléments

In [55]:
x = np.random.rand(5); x
x.mean()

0.39465119580916086

#### Q14 : En utilisant une fonction, donner la taille de la liste suivante :
```python 
l = [x for x in range(11)]
```

In [7]:
l = [k for k in range(11)]
ar = np.size(l); ar


11

#### Q15 : Créer un tableau de taille 10 avec des valeurs comprises entre 0 et 1 EXCLUS 

In [14]:
a = np.random.rand(1,10); a


array([[0.35936992, 0.84966257, 0.52753752, 0.56868504, 0.47516292,
        0.78180166, 0.65321131, 0.99530824, 0.09375   , 0.53924221]])

#### Q16 : Soit deux tableau A et B de dimension 1 et de taille 5, créer A et B et afficher True si A et B sont égaux False sinon

In [19]:
A = np.array([1,2,3,5,4])
B = np.array([1,2,3,5,4])

if (A.ndim == B.ndim ) :
    print('True')
else:
    print('False')


True


#### Q17 : Convertir un tableau de float32 de dimension 1 et de taille 10 en un tableau de meme taille et dimension mais de type int32

In [35]:
tab1 = np.array([1,2,4,5,6,7,8,9,10],dtype='float32');
type(tab1)
tab1.dtype
tab2 = np.ones(10)
tab2=tab1.astype(int)
tab2.dtype
tab1.dtype


dtype('float32')

#### Q18 : Normaliser une matrice random 5x5 
La normalisation d'un nombre X consiste à lui retirer sa moyenne et a diviser le tout par son écart type 

In [69]:
x = np.random.rand(5,5)*10
x=x.astype(int)
ar=x
an_array=x
print(ar)
arx = ar-ar.mean()
print(arx)
arx=arx/ar.std()
print(arx)

#an_array=np.array([[1,2],[2,1]])
print(an_array)
norm = np.linalg.norm(an_array)
print(norm)
normal_array = an_array/norm
print(normal_array)

[[5 9 7 8 1]
 [4 1 8 6 3]
 [8 6 1 1 2]
 [6 6 3 2 8]
 [0 3 6 5 1]]
[[ 0.6  4.6  2.6  3.6 -3.4]
 [-0.4 -3.4  3.6  1.6 -1.4]
 [ 3.6  1.6 -3.4 -3.4 -2.4]
 [ 1.6  1.6 -1.4 -2.4  3.6]
 [-4.4 -1.4  1.6  0.6 -3.4]]
[[ 0.21879749  1.6774474   0.94812244  1.31278492 -1.23985243]
 [-0.14586499 -1.23985243  1.31278492  0.58345997 -0.51052747]
 [ 1.31278492  0.58345997 -1.23985243 -1.23985243 -0.87518995]
 [ 0.58345997  0.58345997 -0.51052747 -0.87518995  1.31278492]
 [-1.60451491 -0.51052747  0.58345997  0.21879749 -1.23985243]]
[[5 9 7 8 1]
 [4 1 8 6 3]
 [8 6 1 1 2]
 [6 6 3 2 8]
 [0 3 6 5 1]]
25.92296279363144
[[0.19287919 0.34718254 0.27003086 0.3086067  0.03857584]
 [0.15430335 0.03857584 0.3086067  0.23145502 0.11572751]
 [0.3086067  0.23145502 0.03857584 0.03857584 0.07715167]
 [0.23145502 0.23145502 0.11572751 0.07715167 0.3086067 ]
 [0.         0.11572751 0.23145502 0.19287919 0.03857584]]


#### Q19 : Créer une matrice random `M` 2x2 et donner sa transposer 
L'opération de transposition dans une matrice consiste à échanger les lignes et le colonnes. 

In [80]:
M= np.random.randint(0,10,size=(2,2))
print(M)
M.transpose((1,0))

[[7 4]
 [3 7]]


array([[7, 3],
       [4, 7]])

#### Q20 : Écrire un petit script qui remplace un élément au hasard dans une matrice de dimension NxN

In [87]:
# Data size
N = 5

# How many entries to replace
REPLACE_COUNT = 1

# What to replace with
REPLACE_WITH = 555

# Just for clarity of display
#np.set_printoptions(precision=2, suppress=True)

# Generate some data.
data = np.random.randint(0, 20,size=(N,N))

print('Original: ')
print(data)

data.flat[np.random.choice(N * N, REPLACE_COUNT, replace=False)] = REPLACE_WITH
print('\n After replacement: ')
print(data)



# # input array
# x = np.array([[ 1., 2., 3.], [ 4., 5., 6.], [ 7., 8., 9.]])

# # random boolean mask for which values will be changed
# mask = np.random.randint(0,2,size=x.shape).astype(np.bool)

# # random matrix the same shape of your data
# r = np.random.rand(*x.shape)*np.max(x)

# # use your mask to replace values in your input array
# x[mask] = r[mask]
# print(x)

Original: 
[[ 1  0 14  0  4]
 [15 18  3  2 16]
 [16 11 13  5  2]
 [ 8  4 16 13  2]
 [ 0 19  0  2 17]]

 After replacement: 
[[  1   0  14   0   4]
 [ 15  18   3   2  16]
 [ 16 555  13   5   2]
 [  8   4  16  13   2]
 [  0  19   0   2  17]]


#### Q21 : Considérons une matrice de dimension (5,5,3), écrire un script qui multiplie cette matrice par une matrice de dimension (5,5)

In [77]:
np.random.seed(42)

A = np.random.randint(0, 15, size=(3,2))

B = np.random.randint(0, 15, size =(2,4))

print("Matrix A:\n", A)

print("shape of A =", A.shape)

print()

print("Matrix B:\n", B)

print("shape of B =", B.shape)

C = np.matmul(A, B)

print("product of A and B:\n", C)

print("shape of product =", C.shape)

Matrix A:
 [[ 6  3]
 [12 14]
 [10  7]]
shape of A = (3, 2)

Matrix B:
 [[12  4  6  9]
 [ 2  6 10 10]]
shape of B = (2, 4)
product of A and B:
 [[ 78  42  66  84]
 [172 132 212 248]
 [134  82 130 160]]
shape of product = (3, 4)
